# Generated by Django 5.2.14 on 2026-05-18 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demands', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='demand',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='demands/%Y/%m/', verbose_name='Imagem'),
        ),
    ]
